# Generated by Django 3.1.7 on 2021-02-20 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wantoitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_url', models.URLField()),
                ('main_title', models.CharField(max_length=255)),
                ('wantoitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wantoitem')),
            ],
        ),
        migrations.CreateModel(
            name='Except',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('except_url', models.URLField()),
                ('except_title', models.CharField(max_length=255)),
                ('wantoitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wantoitem')),
            ],
        ),
    ]
