# Generated by Django 3.1.7 on 2021-02-21 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210222_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub',
            old_name='except_title',
            new_name='sub_title',
        ),
        migrations.RenameField(
            model_name='sub',
            old_name='except_url',
            new_name='sub_url',
        ),
    ]
