# Generated by Django 3.1.7 on 2021-02-22 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210222_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_maker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='wantoitem',
            name='maker_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app.item_maker'),
        ),
        migrations.AddField(
            model_name='wantoitem',
            name='tag',
            field=models.ManyToManyField(blank=True, to='app.Tag'),
        ),
    ]
