# Generated by Django 3.1.7 on 2021-02-22 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210222_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantoitem',
            name='maker_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.item_maker'),
        ),
    ]
