# Generated by Django 3.1.7 on 2021-02-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210223_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantoitem',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
