# Generated by Django 3.1.7 on 2021-02-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_wantoitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantoitem',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
