# Generated by Django 3.1.7 on 2021-02-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210223_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='main_ogp_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sub',
            name='sub_ogp_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
