# Generated by Django 3.1.7 on 2021-02-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210224_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantoitem',
            name='maker_slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
