# Generated by Django 3.1.7 on 2021-02-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210225_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_maker',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
