# Generated by Django 3.1.7 on 2021-03-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_item_category_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_category',
            name='url',
            field=models.URLField(max_length=255),
        ),
    ]
